# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20160405_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='parsed',
            field=models.TextField(help_text="Pas hier de opdeling van de kookles in recepten aan. De titel van elk recept wordt aangegeven met ## titel, en ingredienten met | ingredient |. Als je klaar bent klik dan op 'save and continue editing' en op 'view on site'", null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Lesson'),
        ),
    ]
