# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20160412_2307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('recipe', 'user')]),
        ),
    ]
