# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20160412_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='insertdate', default=datetime.datetime(2016, 4, 12, 23, 17, 44, 962256, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
