# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20160422_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-favourite', 'date']},
        ),
        migrations.AddField(
            model_name='picture',
            name='image_small',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='picture',
            name='image_thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
