# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20160425_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='aanwezig',
            field=models.TextField(blank=True, null=True),
        ),
    ]
