# Generated by Django 3.2.18 on 2026-03-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_fts5_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menurecipe',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='menu',
            name='recipes',
            field=models.ManyToManyField(through='recipes.MenuRecipe', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='docfile',
            field=models.FileField(upload_to='lessons'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_small',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_thumb',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
